version: '3.8'

networks:
  steg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  sender:
    image: r3xonx/steg_lsb-png.sender:latest
    container_name: steg_sender
    hostname: sender
    networks:
      steg_network:
        ipv4_address: 172.21.0.20
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash"]

  receiver:
    image: r3xonx/steg_lsb-png.receiver:latest
    container_name: steg_receiver
    hostname: receiver
    networks:
      steg_network:
        ipv4_address: 172.21.0.30
    tty: true
    stdin_open: true
    restart: unless-stopped
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash"]
